language: node_js
node_js:
  - "node"
branches:
  only:
  - releases
script: npm run build
deploy:
  - provider: heroku
    api_key:
      secure: DUKWLXdAjjd90eP9tK+YSW7XeDPF842v2sHWNg6TnR3Lr1zwVo9IASFGKPp7NV9EpvU81tt1J2SsiveFIi0dtul5hWpmQOKzm0DdE9QcFWLVGTsI7oZuUpyGPOkTwscnOFkX55dqyzfcmcnwPTU0FkFx2yLrfbo60PBABcSwawX+yME91osXgYo6tflqLDmTWJ5xhDLW2IwvQcMvTTwJw3a2+tiP8JMEn7OhTpJq5YKenUR25+eyiopApaUPkFtH1V8hGSH7MHpMUHqR8KxsZvsnWD/Ddd8NHkV8g9CBClaKhZP97Tl6aQxEyRCtnM/VzvZp02LFYCFfC8sQTREXz01cx0N9roSf6w12Y5V4DawyoJ5igP00aUFOCAPb3WicqJnhgcrhcreDmhN7alJrAoGB17uU8AnPRyVvEDIIJBWT/J7wuO48ybzBKm3nbev4Df/P2IQwtXEpynW75Eywca/UADUOn1UxE+hLgC1gbQekU5W+dSS1QNm0NuStS0YhTOrpP+j/iHQMjoOtfZTHeAW59OSVGeK9oraRGurhYaVdpW+7NbeCEEBLPAuuY3SkPkHRFctCYgoPz7QqZVQZa7iYZ/Za9H1iDiKnQtGCE9DsBJHMSm2ucEVZpLvD0xb8IEExZIC39gpxwAfM8Ru6/3g5ELnu4kaRJDKno2XlD4c=
    app: slv-timeasr
    skip_cleanup: true
    on: releases
  - provider: openshift
    user: lsolova
    password: UlDJUfImgORO1ITyjVwvVqouWH7XxmywjGptmNgRjDB3GIdU44OCK56TGcdcTCOEhuFBYYKi85Ez8Chl0hqBKjbtUaUYVNKsTvFsU8IdS27wntmcr0hHIlvOOhJfrNfeR4Q+H3LSksCcfeC5KCverzvrpleGrCFsgrL1GzlWMbZPugF1nz9/g4pmtCqRAxgyrIoEUVRUcxh4K8X6TqkttJpS/JdT05+btWPlFtt0inSqZae8VALGrAwGOTmfzUCzQjJkdHIzwdGrxW/F5oeQFMTQM9lERsux5RyFPvZC3mKLHvwzrNnXtUh340Bnq+cOqTjYQFDUpC27iP08iarzJxhLe0szAdjssohMFB6VKpbxsk79+DLwzDYi7LchQUYckeMDb/BbMFerHIWf5uhkXVHm0rSQFc0eeuUrcYffPebTzQOpTmYV3YAGWmqLBA3npl0kaxiDaesgmsSv1Uv4lREvzcDxte0KPvqjwcD7efPwnIVQoLCZFu7tBPQ6Nm7/jAqr3fiB+iuKCPk6Quju4fPzeC8Olq93ebC2GpReGG5LdXVEPVQDep4079j4gbktDkn8YuW72dPtyX7dNfK4CAVickbX9Zi4sBU9jGDzRmO2hppsI/Z+6wG4iFmWBDonnDQXZKvJzAi5O30p2hrVNGdmSCUhcyafKeheQwWi4TI=
    domain: timeasr.solova.com
    app: slv-timeasr
    on: releases
