@startuml
skinparam shadowing false

[Application] as app
' "Views" {
  [MeasureView] as mw
  [SettingsView] as sw
'}
'package "Controllers" {
  [MeasureController] as mc
  [SettingsController] as sc
'}
'package "Utils" {
  [TimeCalcUtils] as tcau
  [TimeConversionUtils] as tcou
'}
'package "Data storage" {
  [MeasureTime] as mt
  [ModelHandler] as mh
  [PersistentStore] as ps
  [TimeLogService] as tls
  [TimeLogPersistingService] as tlps
'}
  
app ..> mc
app ..> mw
app ..> sc
app ..> sw
mc ..> mh
mc ..> tcau
mc ..> tcou
mc ..> tls
mh ..> ps
mh ..> tcou
mt ..> tcou
mw ..> mc
mw ..> tcou
sc ..> mh
sc ..> tcau
sc ..> tcou
sc ..> tls
sw ..> sc
sw ..> tcou
tcau ..> tcou
tlps ..> ps
tls ..> tcou
tls ..> tlps

@enduml
