
name: Build Timeasr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        yarn install
        yarn build